spring:
  application:
    name: 'wombatu-bot'

  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: none
    show-sql: false

  datasource:
    url: 'jdbc:postgresql://localhost:5432/wombatubot'
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximum-pool-size: 60
    continue-on-error: false

  liquibase:
    change-log: classpath:db/db.changelog-master.xml

  jackson:
    default-property-inclusion: non_null


logging:
  file: bot.log
  level:
    root: INFO
    liquibase: WARN
    wombatukun.bots.wombatubot: DEBUG

telegram:
  botUsername: ${TELEGRAM_BOTUSERNAME}
  botToken: ${TELEGRAM_BOTTOKEN}
  botAdmin: ${TELEGRAM_BOTADMIN}
  transmitterOn: true

apis:
  cbr:
    url: https://www.cbr.ru/scripts/XML_daily.asp?date_req=
