logging:
  file: bot.log
  level:
    root: INFO
    liquibase: WARN
    wombatukun.bots.wombatubot: DEBUG

telegram:
  botUsername: ${TELEGRAM_BOTUSERNAME}
  botToken: ${TELEGRAM_BOTTOKEN}

apis:
  cbr:
    url: https://www.cbr.ru/scripts/XML_daily.asp?date_req=
